export const ITEM_CATALOG = [
  { id: "avatar_student", name: "Student", type: "avatar", tier: "common", gemPrice: 5, imageData: "avatar_student", description: "A cheerful student ready to learn" },
  { id: "avatar_worker", name: "Office Worker", type: "avatar", tier: "common", gemPrice: 5, imageData: "avatar_worker", description: "Professional and focused" },
  { id: "avatar_casual", name: "Casual", type: "avatar", tier: "common", gemPrice: 5, imageData: "avatar_casual", description: "Laid-back and cool" },
  { id: "avatar_sporty", name: "Sporty", type: "avatar", tier: "common", gemPrice: 5, imageData: "avatar_sporty", description: "Always on the move" },
  { id: "avatar_mage", name: "Mage", type: "avatar", tier: "uncommon", gemPrice: 15, imageData: "avatar_mage", description: "Wielder of arcane magic" },
  { id: "avatar_knight", name: "Knight", type: "avatar", tier: "uncommon", gemPrice: 15, imageData: "avatar_knight", description: "Brave and honorable" },
  { id: "avatar_ninja", name: "Ninja", type: "avatar", tier: "uncommon", gemPrice: 15, imageData: "avatar_ninja", description: "Silent and deadly" },
  { id: "avatar_pirate", name: "Pirate", type: "avatar", tier: "uncommon", gemPrice: 15, imageData: "avatar_pirate", description: "Sea rover" },
  { id: "avatar_monk", name: "Monk", type: "avatar", tier: "uncommon", gemPrice: 15, imageData: "avatar_monk", description: "Martial artist" },
  { id: "avatar_celestial", name: "Celestial Guardian", type: "avatar", tier: "rare", gemPrice: 30, imageData: "avatar_celestial", description: "Blessed by the stars" },
  { id: "avatar_forest", name: "Forest Spirit", type: "avatar", tier: "rare", gemPrice: 30, imageData: "avatar_forest", description: "One with nature" },
  { id: "avatar_samurai", name: "Samurai", type: "avatar", tier: "rare", gemPrice: 30, imageData: "avatar_samurai", description: "Blade master" },
  { id: "avatar_elementalist", name: "Elementalist", type: "avatar", tier: "rare", gemPrice: 30, imageData: "avatar_elementalist", description: "Force of nature" },
  { id: "avatar_crystal", name: "Crystal Mage", type: "avatar", tier: "epic", gemPrice: 60, imageData: "avatar_crystal", description: "Power crystallized into form" },
  { id: "avatar_shadow", name: "Shadow Warrior", type: "avatar", tier: "epic", gemPrice: 60, imageData: "avatar_shadow", description: "Born from darkness" },
  { id: "avatar_paladin", name: "Paladin", type: "avatar", tier: "epic", gemPrice: 60, imageData: "avatar_paladin", description: "Holy warrior" },
  { id: "avatar_vampire", name: "Vampire", type: "avatar", tier: "epic", gemPrice: 60, imageData: "avatar_vampire", description: "Lord of darkness" },
  { id: "avatar_dragon", name: "Dragon Tamer", type: "avatar", tier: "legendary", gemPrice: 120, imageData: "avatar_dragon", description: "Commands the ancient dragons" },
  { id: "avatar_emperor", name: "Celestial Emperor", type: "avatar", tier: "mythic", gemPrice: 500, imageData: "avatar_emperor", description: "Ruler of all realms", isGachaEligible: false, requiredLevel: 7, requiredTasks: 50 },

  { id: "card_basic", name: "Basic", type: "card", tier: "common", gemPrice: 5, imageData: "border-slate-300 bg-gradient-to-br from-slate-50 to-slate-100", description: "Clean and simple" },
  { id: "card_minimal", name: "Minimal", type: "card", tier: "common", gemPrice: 5, imageData: "border-gray-200 bg-white", description: "Less is more" },
  { id: "card_classic", name: "Classic", type: "card", tier: "common", gemPrice: 5, imageData: "border-amber-300 bg-gradient-to-br from-amber-50 to-yellow-50", description: "Timeless elegance" },
  { id: "card_retro", name: "Retro", type: "card", tier: "common", gemPrice: 5, imageData: "border-orange-300 bg-gradient-to-br from-orange-50 to-red-50", description: "Old school vibes" },
  { id: "card_ember", name: "Ember", type: "card", tier: "common", gemPrice: 5, imageData: "border-orange-400 bg-gradient-to-br from-orange-950 to-red-950", description: "Burning ember" },
  { id: "card_frost", name: "Frost", type: "card", tier: "common", gemPrice: 5, imageData: "border-blue-400 bg-gradient-to-br from-blue-950 to-cyan-950", description: "Frozen ice" },
  { id: "card_shadow", name: "Shadow", type: "card", tier: "common", gemPrice: 5, imageData: "border-gray-500 bg-gradient-to-br from-gray-950 to-black", description: "Dark void" },
  { id: "card_sakura", name: "Sakura", type: "card", tier: "uncommon", gemPrice: 15, imageData: "border-pink-300 bg-gradient-to-br from-pink-50 to-rose-100", description: "Cherry blossom dreams" },
  { id: "card_ocean", name: "Ocean Wave", type: "card", tier: "uncommon", gemPrice: 15, imageData: "border-blue-300 bg-gradient-to-br from-blue-50 to-cyan-100", description: "Calm ocean waves" },
  { id: "card_starry", name: "Starry Night", type: "card", tier: "uncommon", gemPrice: 15, imageData: "border-indigo-300 bg-gradient-to-br from-indigo-50 to-violet-100", description: "Under the stars" },
  { id: "card_blood", name: "Blood Moon", type: "card", tier: "uncommon", gemPrice: 15, imageData: "border-red-500 bg-gradient-to-br from-red-950 to-rose-950", description: "Blood moon" },
  { id: "card_thunder", name: "Lightning Strike", type: "card", tier: "uncommon", gemPrice: 15, imageData: "border-yellow-500 bg-gradient-to-br from-yellow-950 to-amber-950", description: "Lightning strike" },
  { id: "card_void", name: "The Void", type: "card", tier: "uncommon", gemPrice: 15, imageData: "border-indigo-500 bg-gradient-to-br from-indigo-950 to-violet-950", description: "The void" },
  { id: "card_golden", name: "Golden Frame", type: "card", tier: "rare", gemPrice: 30, imageData: "border-yellow-400 bg-gradient-to-br from-yellow-50 to-amber-100", description: "Touched by gold" },
  { id: "card_crystal_glow", name: "Crystal Glow", type: "card", tier: "rare", gemPrice: 30, imageData: "border-cyan-400 bg-gradient-to-br from-cyan-50 to-teal-100", description: "Crystalline beauty" },
  { id: "card_dragon_fire", name: "Dragon's Breath", type: "card", tier: "rare", gemPrice: 30, imageData: "border-red-600 bg-gradient-to-br from-red-900 via-orange-900 to-yellow-900", description: "Dragon's breath" },
  { id: "card_ice_queen", name: "Ice Queen", type: "card", tier: "rare", gemPrice: 30, imageData: "border-cyan-400 bg-gradient-to-br from-cyan-950 via-blue-950 to-purple-950", description: "Ice queen" },
  { id: "card_aurora", name: "Aurora", type: "card", tier: "epic", gemPrice: 60, imageData: "border-emerald-400 bg-gradient-to-br from-green-50 via-cyan-50 to-purple-100", description: "Northern lights" },
  { id: "card_nebula", name: "Nebula", type: "card", tier: "epic", gemPrice: 60, imageData: "border-purple-400 bg-gradient-to-br from-purple-50 via-pink-50 to-blue-100", description: "Cosmic wonder" },
  { id: "card_shadow_lord", name: "Shadow Overlord", type: "card", tier: "epic", gemPrice: 60, imageData: "border-purple-600 bg-gradient-to-br from-purple-950 via-gray-950 to-black", description: "Shadow overlord" },
  { id: "card_phoenix", name: "Phoenix Rising", type: "card", tier: "epic", gemPrice: 60, imageData: "border-orange-500 bg-gradient-to-br from-red-900 via-orange-900 to-yellow-900", description: "Phoenix rising" },
  { id: "card_temple", name: "Cherry Blossom Temple", type: "card", tier: "legendary", gemPrice: 120, imageData: "border-rose-400 bg-gradient-to-br from-rose-50 via-pink-50 to-red-100", description: "Sacred garden temple" },
  { id: "card_world_tree", name: "World Tree", type: "card", tier: "legendary", gemPrice: 120, imageData: "border-green-500 bg-gradient-to-br from-green-950 via-emerald-900 to-cyan-950", description: "World tree" },
  { id: "card_cosmic", name: "Cosmic Throne", type: "card", tier: "mythic", gemPrice: 500, imageData: "border-violet-500 bg-gradient-to-br from-violet-100 via-purple-100 to-indigo-200", description: "Seat of the cosmos", isGachaEligible: false, requiredLevel: 7, requiredTasks: 50 },

  { id: "equip_straw_hat", name: "Straw Hat", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "head", imageData: "equip_straw_hat", description: "A simple straw hat" },
  { id: "equip_bandana", name: "Bandana", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "head", imageData: "equip_bandana", description: "Cool headwear" },
  { id: "equip_hood", name: "Dark Hood", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "head", imageData: "equip_hood", description: "Dark hood" },
  { id: "equip_helmet", name: "Iron Helmet", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "head", imageData: "equip_helmet", description: "Iron helmet" },
  { id: "equip_glasses", name: "Glasses", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "face", imageData: "equip_glasses", description: "Smart and stylish" },
  { id: "equip_sunglasses", name: "Sunglasses", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "face", imageData: "equip_sunglasses", description: "Too cool for school" },
  { id: "equip_eye_patch", name: "Eye Patch", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "face", imageData: "equip_eye_patch", description: "Eye patch" },
  { id: "equip_simple_cape", name: "Simple Cape", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "body", imageData: "equip_simple_cape", description: "A basic cape" },
  { id: "equip_leather_armor", name: "Leather Armor", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "body", imageData: "equip_leather_armor", description: "Leather armor" },
  { id: "equip_robes", name: "Mystic Robes", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "body", imageData: "equip_robes", description: "Mystic robes" },
  { id: "equip_soft_glow", name: "Soft Glow", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "aura", imageData: "equip_soft_glow", description: "A gentle aura" },
  { id: "equip_smoke", name: "Smoke Aura", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "aura", imageData: "equip_smoke", description: "Smoke aura" },
  { id: "equip_wind", name: "Wind Swirl", type: "equipment", tier: "common", gemPrice: 5, equipSlot: "aura", imageData: "equip_wind", description: "Wind swirl" },
  { id: "equip_crown", name: "Crown", type: "equipment", tier: "uncommon", gemPrice: 15, equipSlot: "head", imageData: "equip_crown", description: "Fit for royalty" },
  { id: "equip_flower_crown", name: "Flower Crown", type: "equipment", tier: "uncommon", gemPrice: 15, equipSlot: "head", imageData: "equip_flower_crown", description: "Nature's crown" },
  { id: "equip_wolf_mask", name: "Wolf Mask", type: "equipment", tier: "uncommon", gemPrice: 15, equipSlot: "head", imageData: "equip_wolf_mask", description: "Wolf mask" },
  { id: "equip_mask", name: "Mystery Mask", type: "equipment", tier: "uncommon", gemPrice: 15, equipSlot: "face", imageData: "equip_mask", description: "Hide your identity" },
  { id: "equip_war_paint", name: "War Paint", type: "equipment", tier: "uncommon", gemPrice: 15, equipSlot: "face", imageData: "equip_war_paint", description: "War paint" },
  { id: "equip_chainmail", name: "Chainmail", type: "equipment", tier: "uncommon", gemPrice: 15, equipSlot: "body", imageData: "equip_chainmail", description: "Chainmail" },
  { id: "equip_trench_coat", name: "Trench Coat", type: "equipment", tier: "uncommon", gemPrice: 15, equipSlot: "body", imageData: "equip_trench_coat", description: "Trench coat" },
  { id: "equip_lightning", name: "Lightning Aura", type: "equipment", tier: "uncommon", gemPrice: 15, equipSlot: "aura", imageData: "equip_lightning", description: "Lightning aura" },
  { id: "equip_dark_mist", name: "Dark Mist", type: "equipment", tier: "uncommon", gemPrice: 15, equipSlot: "aura", imageData: "equip_dark_mist", description: "Dark mist" },
  { id: "equip_crystal_armor", name: "Crystal Armor", type: "equipment", tier: "rare", gemPrice: 30, equipSlot: "body", imageData: "equip_crystal_armor", description: "Forged from crystals" },
  { id: "equip_fire_aura", name: "Fire Aura", type: "equipment", tier: "rare", gemPrice: 30, equipSlot: "aura", imageData: "equip_fire_aura", description: "Burning with determination" },
  { id: "equip_halo", name: "Divine Halo", type: "equipment", tier: "rare", gemPrice: 30, equipSlot: "head", imageData: "equip_halo", description: "Divine halo" },
  { id: "equip_cyber_visor", name: "Cyber Visor", type: "equipment", tier: "rare", gemPrice: 30, equipSlot: "face", imageData: "equip_cyber_visor", description: "Cyber visor" },
  { id: "equip_dragon_scale", name: "Dragon Scale Armor", type: "equipment", tier: "rare", gemPrice: 30, equipSlot: "body", imageData: "equip_dragon_scale", description: "Dragon scale armor" },
  { id: "equip_ice_aura", name: "Frost Aura", type: "equipment", tier: "rare", gemPrice: 30, equipSlot: "aura", imageData: "equip_ice_aura", description: "Frost aura" },
  { id: "equip_dragon_horns", name: "Dragon Horns", type: "equipment", tier: "epic", gemPrice: 60, equipSlot: "head", imageData: "equip_dragon_horns", description: "Ancient dragon power" },
  { id: "equip_dragon_crown", name: "Dragon Crown", type: "equipment", tier: "epic", gemPrice: 60, equipSlot: "head", imageData: "equip_dragon_crown", description: "Dragon crown" },
  { id: "equip_crystal_eye", name: "Crystal Eye", type: "equipment", tier: "epic", gemPrice: 60, equipSlot: "face", imageData: "equip_crystal_eye", description: "Sees all, knows all" },
  { id: "equip_third_eye", name: "Third Eye", type: "equipment", tier: "epic", gemPrice: 60, equipSlot: "face", imageData: "equip_third_eye", description: "Third eye" },
  { id: "equip_shadow_cloak", name: "Shadow Cloak", type: "equipment", tier: "epic", gemPrice: 60, equipSlot: "body", imageData: "equip_shadow_cloak", description: "Shadow cloak" },
  { id: "equip_holy_light", name: "Holy Radiance", type: "equipment", tier: "epic", gemPrice: 60, equipSlot: "aura", imageData: "equip_holy_light", description: "Holy radiance" },
  { id: "equip_cosmic_aura", name: "Cosmic Aura", type: "equipment", tier: "legendary", gemPrice: 120, equipSlot: "aura", imageData: "equip_cosmic_aura", description: "The universe within" },
  { id: "equip_phantom_hood", name: "Phantom Hood", type: "equipment", tier: "legendary", gemPrice: 120, equipSlot: "head", imageData: "equip_phantom_hood", description: "Phantom hood" },
  { id: "equip_demon_eyes", name: "Demon Eyes", type: "equipment", tier: "legendary", gemPrice: 120, equipSlot: "face", imageData: "equip_demon_eyes", description: "Demon eyes" },
  { id: "equip_titan_armor", name: "Titan Armor", type: "equipment", tier: "legendary", gemPrice: 120, equipSlot: "body", imageData: "equip_titan_armor", description: "Titan armor" },
  { id: "equip_black_hole", name: "Black Hole", type: "equipment", tier: "legendary", gemPrice: 120, equipSlot: "aura", imageData: "equip_black_hole", description: "Black hole" },
  { id: "equip_worldender", name: "Worldender Robe", type: "equipment", tier: "mythic", gemPrice: 500, equipSlot: "body", imageData: "equip_worldender", description: "Power beyond mortal comprehension", isGachaEligible: false, requiredLevel: 7, requiredTasks: 50 },
  { id: "equip_void_energy", name: "Void Energy", type: "equipment", tier: "mythic", gemPrice: 500, equipSlot: "aura", imageData: "equip_void_energy", description: "Void energy", isGachaEligible: false, requiredLevel: 7, requiredTasks: 50 },
] as const;

export type ItemCatalogEntry = (typeof ITEM_CATALOG)[number];

export const TIER_COLORS: Record<string, string> = {
  common: "bg-gray-800/50 text-gray-300 border-gray-600",
  uncommon: "bg-green-900/30 text-green-400 border-green-500/50",
  rare: "bg-cyan-900/30 text-cyan-400 border-cyan-500/50",
  epic: "bg-purple-900/30 text-purple-400 border-purple-500/50",
  legendary: "bg-yellow-900/30 text-yellow-400 border-yellow-500/50",
  mythic: "bg-red-900/30 text-red-400 border-red-500/50",
};

export const TIER_BORDER: Record<string, string> = {
  common: "border-gray-600",
  uncommon: "border-green-500/50",
  rare: "border-cyan-500/50",
  epic: "border-purple-500/50",
  legendary: "border-yellow-500/50",
  mythic: "border-red-500/50",
};

export const TIER_GLOW: Record<string, string> = {
  common: "",
  uncommon: "shadow-green-500/20",
  rare: "shadow-cyan-500/20",
  epic: "shadow-purple-500/30 shadow-lg",
  legendary: "shadow-yellow-500/30 shadow-lg",
  mythic: "shadow-red-500/40 shadow-xl",
};
