import React from "react";

type IconProps = {
  size?: number;
  className?: string;
  style?: React.CSSProperties;
};

import {
  KatanaIcon,
  ShieldIcon,
  GemIcon,
  FlameIcon,
  SkullIcon,
  EyeIcon,
  DragonIcon,
  StarIcon,
  CrownIcon,
  MaskIcon,
  HaloIcon,
  HornsIcon,
  ThunderIcon,
  SpiralIcon,
  WindIcon,
  SmokeIcon,
  IceIcon,
  CosmicIcon,
  BookIcon,
  PaletteIcon,
  UsersIcon,
  HeartIcon,
  DumbbellIcon,
  TargetIcon,
  WrenchIcon,
  CheckIcon,
  TrophyIcon,
  ScrollIcon,
  SettingsIcon,
  SparkleIcon,
  MoonIcon,
  CyborgIcon,
  ClawIcon,
  CrossIcon,
  GhostIcon,
  VisorIcon,
  ArmorIcon,
  HatIcon,
  BandanaIcon,
  HoodIcon,
  HelmetIcon,
  GlassesIcon,
  SunglassesIcon,
  CapeIcon,
  ChainIcon,
  BladeIcon,
  CloverIcon,
  RosetteIcon,
  SunIcon,
  ChartIcon,
  GiftIcon,
  SearchIcon,
  StreakIcon,
  SeedIcon,
  SproutIcon,
  WarningIcon,
  GavelIcon,
  CalendarIcon,
  DiceIcon,
} from "./Icons";

const iconMap: Record<string, React.FC<IconProps>> = {
  avatar_student: SunIcon,
  avatar_worker: TargetIcon,
  avatar_casual: SunglassesIcon,
  avatar_sporty: DumbbellIcon,
  avatar_mage: StarIcon,
  avatar_knight: KatanaIcon,
  avatar_ninja: MaskIcon,
  avatar_pirate: BladeIcon,
  avatar_monk: FlameIcon,
  avatar_celestial: HaloIcon,
  avatar_forest: SproutIcon,
  avatar_samurai: BladeIcon,
  avatar_elementalist: SpiralIcon,
  avatar_crystal: GemIcon,
  avatar_shadow: MoonIcon,
  avatar_paladin: ShieldIcon,
  avatar_vampire: SkullIcon,
  avatar_dragon: DragonIcon,
  avatar_emperor: CrownIcon,
  equip_straw_hat: HatIcon,
  equip_bandana: BandanaIcon,
  equip_hood: HoodIcon,
  equip_helmet: HelmetIcon,
  equip_glasses: GlassesIcon,
  equip_sunglasses: SunglassesIcon,
  equip_eye_patch: CyborgIcon,
  equip_simple_cape: CapeIcon,
  equip_leather_armor: ArmorIcon,
  equip_robes: ScrollIcon,
  equip_soft_glow: SparkleIcon,
  equip_smoke: SmokeIcon,
  equip_wind: WindIcon,
  equip_crown: CrownIcon,
  equip_flower_crown: RosetteIcon,
  equip_wolf_mask: MaskIcon,
  equip_mask: GhostIcon,
  equip_war_paint: PaletteIcon,
  equip_chainmail: ChainIcon,
  equip_trench_coat: CapeIcon,
  equip_lightning: ThunderIcon,
  equip_dark_mist: SmokeIcon,
  equip_crystal_armor: ShieldIcon,
  equip_fire_aura: FlameIcon,
  equip_halo: HaloIcon,
  equip_cyber_visor: VisorIcon,
  equip_dragon_scale: DragonIcon,
  equip_ice_aura: IceIcon,
  equip_dragon_horns: HornsIcon,
  equip_dragon_crown: CrownIcon,
  equip_crystal_eye: EyeIcon,
  equip_third_eye: EyeIcon,
  equip_shadow_cloak: MoonIcon,
  equip_holy_light: CrossIcon,
  equip_cosmic_aura: CosmicIcon,
  equip_phantom_hood: GhostIcon,
  equip_demon_eyes: SkullIcon,
  equip_titan_armor: ArmorIcon,
  equip_black_hole: SpiralIcon,
  equip_worldender: ThunderIcon,
  equip_void_energy: SpiralIcon,
};

export function getItemIcon(id: string, props?: IconProps) {
  const Icon = iconMap[id];
  if (Icon) return <Icon {...props} />;
  return <KatanaIcon {...props} />;
}

const categoryIconMap: Record<string, React.FC<IconProps>> = {
  work: TargetIcon,
  personal: HeartIcon,
  health: StreakIcon,
  study: BookIcon,
  creative: PaletteIcon,
  social: UsersIcon,
  fitness: DumbbellIcon,
};

export function getCategoryIcon(category: string, props?: IconProps) {
  const Icon = categoryIconMap[category];
  if (Icon) return <Icon {...props} />;
  return <KatanaIcon {...props} />;
}

const stageIconMap: Record<string, React.FC<IconProps>> = {
  seed: SeedIcon,
  sprout: SproutIcon,
  budding: FlameIcon,
  blooming: StarIcon,
  withered: SkullIcon,
};

export function getStageIcon(stage: string, props?: IconProps) {
  const Icon = stageIconMap[stage];
  if (Icon) return <Icon {...props} />;
  return <SeedIcon {...props} />;
}

const uiIconMap: Record<string, React.FC<IconProps>> = {
  sword: KatanaIcon,
  gem: GemIcon,
  trophy: TrophyIcon,
  streak: StreakIcon,
  settings: SettingsIcon,
  search: SearchIcon,
  gift: GiftIcon,
  check: CheckIcon,
  chart: ChartIcon,
  crown: CrownIcon,
  warning: WarningIcon,
  gavel: GavelIcon,
  calendar: CalendarIcon,
  dice: DiceIcon,
  users: UsersIcon,
};

export { uiIconMap };

export {
  KatanaIcon,
  ShieldIcon,
  GemIcon,
  FlameIcon,
  SkullIcon,
  EyeIcon,
  DragonIcon,
  StarIcon,
  CrownIcon,
  MaskIcon,
  HaloIcon,
  HornsIcon,
  ThunderIcon,
  SpiralIcon,
  WindIcon,
  SmokeIcon,
  IceIcon,
  CosmicIcon,
  BookIcon,
  PaletteIcon,
  UsersIcon,
  HeartIcon,
  DumbbellIcon,
  TargetIcon,
  WrenchIcon,
  CheckIcon,
  TrophyIcon,
  ScrollIcon,
  SettingsIcon,
  SparkleIcon,
  MoonIcon,
  CyborgIcon,
  ClawIcon,
  CrossIcon,
  GhostIcon,
  VisorIcon,
  ArmorIcon,
  HatIcon,
  BandanaIcon,
  HoodIcon,
  HelmetIcon,
  GlassesIcon,
  SunglassesIcon,
  CapeIcon,
  ChainIcon,
  BladeIcon,
  CloverIcon,
  RosetteIcon,
  SunIcon,
  ChartIcon,
  GiftIcon,
  SearchIcon,
  StreakIcon,
  SeedIcon,
  SproutIcon,
  WarningIcon,
  GavelIcon,
  CalendarIcon,
  DiceIcon,
};
